# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
workspace 'GenericAPP'

target 'ravenProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'

  target 'ravenProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ravenProjectUITests' do
    # Pods for testing
  end

end
